apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip-vip
spec:
  type: ClusterIP
  clusterIP: 10.4.12.88
  selector:
    app: sample-app
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: 80
