apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  externalIPs:
  - 10.146.0.32
  - 10.146.0.31
  selector:
    app: sample-app
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: 80
