apiVersion: v1
kind: Service
metadata:
  name: sample-lb
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
  - name: "http-port"
    port: 8080
    targetPort: 80
    nodePort: 30082
