apiVersion: v1
kind: Pod
metadata:
  name: sample-node-affinity-fail
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - nvme
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: kubernetes.io/hostname 
            operator: In
            values:
            - gke-k8s-default-pool-e2e4ee14-j9qx
        weight: 1
