apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-affinity-zone-host
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: failure-domain.beta.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - sample-app
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - sample-app
          topologyKey: kubernetes.io/hostname
        weight: 1
