apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-resource
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.16
        resources:
          requests: # Minimum value
            memory: 1024Mi
            cpu: 500m
          limits: # Maximum value
            memory: 2048Mi
            cpu: 1000m
